apiVersion: v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: docker.io/vikunja/vikunja:0.23.0
          ports:
            - containerPort: 3456
              hostPort: 8084
          env:
            - name: VIKUNJA_SERVICE_TIMEZONE
              value: UTC
            - name: VIKUNJA_DATABASE_PATH
              value: /db/vikunja.db
          volumeMounts:
            - name: vikunja-db
              mountPath: /db
              readOnly: false
            - name: vikunja-files
              mountPath: /app/vikunja/files
              readOnly: false
      volumes:
        - name: vikunja-db
          hostPath:
            path: /raid/apps/vikunja/db
            type: Directory
        - name: vikunja-files
          hostPath:
            path: /raid/apps/vikunja/files
            type: Directory
