apiVersion: v1
kind: Pod
metadata:
  name: readarr-pod
spec:
  containers:
    - name: readarr
      image: docker.io/linuxserver/readarr:0.3.14-develop
      restartPolicy: OnFailure
      env:
        - name: PUID
          value: 0
        - name: PGID
          value: 0
      ports:
        - containerPort: 8787
          hostPort: 8082
      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        - name: config
          mountPath: /config
          readOnly: false

  volumes:
    - name: data
      hostPath:
        path: /raid/apps/readarr/data
        type: Directory
    - name: config
      hostPath:
        path: /raid/apps/readarr/config
        type: Directory
